CREATE USER 'phptest'@'localhost' IDENTIFIED BY '12345678';
CREATE DATABASE test_db;
GRANT ALL ON test_db.* TO 'phptest'@'localhost';

USE test_db;
CREATE TABLE USER (id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
		account VARCHAR(30) BINARY NOT NULL,
		password VARCHAR(30) NOT NULL,
		reg_date TIMESTAMP,
		UNIQUE(account));

CREATE TABLE PUBLISH (id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		senderID INT(8) UNSIGNED NOT NULL,
		like_num INT(8) UNSIGNED,
		createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        	title TEXT,
		content TEXT,
		FOREIGN KEY (senderID) REFERENCES USER(id));